[features]
seeds = false
skip-lint = false

[programs.localnet]
ordo_brc = "{Use your key}" 

[programs.devnet]
ordo_brc = "{Use your key}"

[programs.mainnet]
ordo_brc = "{Use your key}"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://white-quiet-glitter.solana-devnet.quiknode.pro/2d4bcbb69148d23b481215ff6c3776ecb183f698/"
wallet = "/home/capsa/.config/solana/testing_wallet.json"

[scripts]
mainnet-deploy = "solana program deploy --program-id target/deploy/baycoin_contract-keypair.json  --max-len 415000 target/deploy/baycoin_contract.so --keypair fares-wallet-key.json --url https://white-quiet-glitter.solana-mainnet.quiknode.pro/2d4bcbb69148d23b481215ff6c3776ecb183f698/"
test-init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/init.ts"
test-change-config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/change-config.ts"
test-create-wrapped-entry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-wrapped-entry.ts"
test-add-user-claim = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/add-user-claim.ts"
test-claim-tokens = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/claim-tokens.ts"
test-burn-tokens = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/burn-tokens.ts"
test-redeem-burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/redeem-burn.ts"

test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**.ts"


reset = "anchor build && anchor deploy"

[test]
upgradeable = true

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"